### ISSUE TITLE
Convert this HTML to WordPress theme

### ISSUE THREAD

**Issue by AbhijithHaridas** [SmruthyJoseph/soraytec#1]
[soraytec_html_design.zip](https://github.com/SmruthyJoseph/soraytec/files/5799978/soraytec_html_design.zip)

**Comment by AbhijithHaridas** [comment]
@SmruthyJoseph I need an **ETA** on this

**Comment by SmruthyJoseph** [comment]
I will complete it in 16-01-2021, Saturday at 6 pm.
