### ISSUE TITLE
Error if a custom field is missing

### ISSUE THREAD

**Issue by AbhijithHaridas** [SmruthyJoseph/soraytec#11]
If I delete a custom filed, the page in which that value is rendered prompts error

`Warning: Illegal string offset 'logo_title' in /opt/lampp/htdocs/demo/wordpress/wp-content/themes/soraytec/front-page.php on line 113`

**Comment by SmruthyJoseph** [comment]
#18 **Error if a custom field is missing** issue resolved

**Comment by SmruthyJoseph** [comment]
#11 Updated if scope and added indentation.
