### ISSUE TITLE
About page History Slider

### ISSUE THREAD

**Issue by AbhijithHaridas** [SmruthyJoseph/soraytec#13]
How is this working?

**Comment by SmruthyJoseph** [comment]
I have used BX slider for the slider.

**Comment by AbhijithHaridas** [comment]
No, I mean entirely

How the history click is coded?
Mention the code responsable

**Comment by SmruthyJoseph** [comment]
I used BX slider for history slider and to code the click function, i gave the **data-slide-index** attribute to the anchor tag. So if I click on the date , it will go to slide which has the same index number.

**Comment by AbhijithHaridas** [comment]
Did you made any custom handling function binded to the anchor tag click event which will take this attribute value and execute code to show that particular slide?

Or is this a functionality of BXSlider?

**Comment by SmruthyJoseph** [comment]
It is a functionality of BX slider. I didn't wrote any custom function for that.

**Comment by AbhijithHaridas** [comment]
@SmruthyJoseph can you update the slide animation to right to the left slide
Also, update the autoplay delay a bit

**Comment by SmruthyJoseph** [comment]
Ok

**Comment by SmruthyJoseph** [comment]
#21 **About page history slider** edited.
