### ISSUE TITLE
Aims CPT not working

### ISSUE THREAD

**Issue by AbhijithHaridas** [SmruthyJoseph/soraytec#6]
Adding an **Aim** will not appear in the front-end

**Comment by AbhijithHaridas** [comment]
@SmruthyJoseph have you found the issue?

**Comment by SmruthyJoseph** [comment]
Yes, I am working on it.

**Comment by AbhijithHaridas** [comment]
@SmruthyJoseph what is the status here?

**Comment by SmruthyJoseph** [comment]
#14 **Aims CPT not working** issue resolved.

**Comment by SmruthyJoseph** [comment]
#14 Aims CPT not working issue resolved.
