### ISSUE TITLE
Aims Style Broken

### ISSUE THREAD

**Issue by AbhijithHaridas** [SmruthyJoseph/soraytec#7]
The Aims design should be an alternative no matter the count is

![#](https://user-images.githubusercontent.com/56345292/105139070-cc9cba00-5b1b-11eb-8444-d988ba73bd33.png)

**Comment by AbhijithHaridas** [comment]
@SmruthyJoseph is this completed?

Why is there no file changes?

**Comment by SmruthyJoseph** [comment]
It is completed. It has file changes. But home page custom field issue doesn't have any file change because i only changed it in the wordpress dashboard so the change not showing in the git.

**Comment by SmruthyJoseph** [comment]
#15 Aims style issues corrected.

**Comment by SmruthyJoseph** [comment]
#7 Updated Aims style classes to make it more efficient.
