### ISSUE TITLE
Make all title upper case

### ISSUE THREAD

**Issue by AbhijithHaridas** [SmruthyJoseph/soraytec#9]
![#](https://user-images.githubusercontent.com/56345292/105141317-facfc900-5b1e-11eb-87b7-0e7e19a612d3.png)

**Comment by AbhijithHaridas** [comment]
Is this completed?

Please leave a comment mentioning me before changing the status to client testing, otherwise how will I get notified

**Comment by SmruthyJoseph** [comment]
Yes, It is completed. 
Ok

**Comment by SmruthyJoseph** [comment]
#17 All title changed to uppercase.

**Comment by SmruthyJoseph** [comment]
#17 All **title** changed to uppercase.
